import Header from "@/components/header";
import "./globals.css";
import { Inter } from "next/font/google"
import { ConvexClientProvider } from "@/components/convex-client-provider";
import { ClerkProvider } from "@clerk/nextjs"
const inter = Inter({subsets: ["latin"]})

export const metadata = {
  title: "SplitMe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${inter.className}`}>
      
      <ConvexClientProvider>
      <Header></Header>
       <main className="min-h-screen">{children}</main> 
       </ConvexClientProvider>
       
      </body>
    </html>
    </ClerkProvider>
  );
}
